### ISSUE TITLE
Logging Path no permission

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#10]
Seit dem Update mit der Implementierung vom Logging, kann ich das Plugin via main.py nicht mehr starten. Eine SlowMo Auswertung des Fenster hat gezeigt, dass scheinbar irgendwas mit system32 nicht berechtigt ist.

Starte ich das Plugin jedoch über die Eingabeaufforderung mit pfad/main.py so funktioniert es, wahrscheinlich weil CMD „mehr Rechte“ hat?
Warum ist der Logging Pfad nicht eh einfach im stskit Verzeichnis wo auch immer gespeichert ist?

**Comment by topological-state** [comment]
das logging ist per default im arbeitsverzeichnis und kann mit der option --log-file geändert werden.

via main.py heisst wohl doppelklick auf das file? dann fehlen dir die umgebungsvariablen und das arbeitsverzeichnis. zum starten per doppelklick, menü oder desktop empfehle ich, eine batch-datei anzulegen, in der zuerst die umgebung gesetzt wird.
