### ISSUE TITLE
Folgezüge haben möglicherweise keine Anschlüsse

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#103]
Im Stellwerk Thunersee ist mir etwas komisch aufgefallen. Der Zug 4228 ist schon länger bei mir im Stellwerk unterwegs und wird auf der Anschlusstabelle in Interlaken nicht angezeigt. 
![image](https://user-images.githubusercontent.com/32222604/216840434-57835fc1-eec6-4a7d-bc48-35f8986c4dcc.png)
Die Mindestumsteigezeit habe ich auf 3 Minuten gesetzt, der Zug wird aber auch bei der Einstellung auf einer Minute nicht angezeigt. Eventuell könnte es eben etwas damit zu tun haben, dass der Zug schon länger im Stellwerk ist und immer wieder die Richtung wechselt.

**Comment by topological-state** [comment]
könnte damit zusammenhängen, dass der zug gleis IO 8 mehrmals befährt.

![Screenshot from 2023-02-11 22-11-51](https://user-images.githubusercontent.com/51272421/218281879-890fbd5c-f1d8-4542-99e1-da17531ad1ca.png)

**Comment by topological-state** [comment]
ankunft von pendelzug wird jetzt richtig erkannt:

![Screenshot from 2023-02-12 12-01-24](https://user-images.githubusercontent.com/51272421/218308027-6a800d4b-a65c-4689-a6cf-60b7456a0ff2.png)
