### ISSUE TITLE
Ticket zeigt nächsten Bahnsteig

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#11]
Das Abfahrtsevent zeigt bei "gleis" den nächsten Bahnsteig an und nicht dort, wo der Zug tatsächlich abgefahren ist. Vielleicht ist dies ein Fehler, oder vielleicht auch gewollt.
Zudem wäre es interessant, auch weitere Fahrplaneinträge im Ticket zu haben oder soll-Zeit des aktuellen Fahrplaneintrags.

**Comment by topological-state** [comment]
das kommt so vom simulator. es ist aber auch nicht immer gleich: manchmal zeigt es das nächste gleis, manchmal das alte. da muss man wohl akzeptieren, dass die relais manchmal etwas langsamer klappern.
