### ISSUE TITLE
Dispositionstool Bildfahrplan (K) scheint nicht mehr zu funktionieren

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#110]
![image](https://user-images.githubusercontent.com/32222604/221967474-957346ba-b33d-4c4b-97c6-5cc7d2fcc67d.png)
Kreuzungen können zwar gesetzt werden und werden als solche angezeigt, eine Korrektur scheint aber nicht gemacht zu werden.

**Comment by topological-state** [comment]
manchmal geht's, manchmal nicht. hab noch nicht verstanden weshalb nicht.
