### ISSUE TITLE
Grafik zeigt letztes Stück nicht an

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#130]
Seit einiger Zeit habe ich irgendwie das Problem, dass in verschiedensten Stellwerken in denen ein Zug endet und auf eine Rückleistung wendet das letzte Teilstück nicht in der Grafik angezeigt wird und komischerweise auch die Folgeverspätungsberechnung nicht korrekt funktioniert.
![image](https://github.com/topological-state/stskit/assets/32222604/d6f54be6-64ca-4335-8d50-416195670d6d)
Ein Blick auf den Zugfahrplan zeigt ganz komisch eine Durchfahrt beim letzten Fahrplanpunkt an.

**Comment by topological-state** [comment]
Bei mir funktioniert es nach wie vor korrekt. Ich habe einen Fix publiziert, mit dem der Zugwechsel richtig erkannt werden sollte.

Das ursprüngliche Problem (das Fahrziel wird fälschlicherweise als Ausfahrt markiert) ist damit nicht gelöst und könnte anderswo auch noch ein Problem verursachen.

Wie sieht der Fahrplan im Sim aus, insb. die Spalte "Nach"? Heisst es da "Gleis SURB" oder nur "SURB"?

**Comment by PianoRailways** [comment]
Danke für den Hinweis "Gleis"... Ich hatte wohl vor ein paar Wochen einmal im Kommunikator die Option Simulator -> kein "Gleis in "nach" aktiviert. Nach dem Deaktivieren davon und einem Spielneustart funktioniert es wieder, auch mit der alten STSdispo Version.

**Comment by topological-state** [comment]
Ach, das kann man abstellen!? stsDispo liest daran ab, ob der Zug ausfährt oder im Stellwerk bleibt. In der nächsten Hauptversion werde ich es an den Flags ablesen.
