### ISSUE TITLE
Darstellung von Zügen mit A Flag

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#14]
In diesem Fall ist es so: 60767 in Olten hat eine Verspätung von 23 Minuten und eine Standzeit von theoretisch 9 Minuten. Dank dem A Flag kann der Zug jedoch früher losgeschickt werden bzw fährt sofort wieder los, wenn die Abfahrtszeit erreicht ist. Somit könnte die Verspätung also um 9 Minuten reduziert werden. Die Gleisbelegung zeigt jedoch nur einen Aufenthalt von einer Minute und die Verspätung von 23 Minuten.
![image](https://user-images.githubusercontent.com/32222604/168842832-850abfc2-1fc1-4afc-82e1-388a5bc6955c.png)

**Comment by topological-state** [comment]
sollte jetzt besser funktionieren.

**Comment by topological-state** [comment]
balken und infobox zeigen jetzt beide die ankunftsverspätung am gewählten gleis an.
