### ISSUE TITLE
Modul Fahrplan (ZID + Suchfunktion)

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#15]
Im neuen Fahrplanmodul, welches nun funktioniert fehlt der Titel ZID in der ersten Spalte. Zudem kann man diese Spalte nicht sortieren, ist zwar eigentlich auch nicht nötig.

Eine Suchfunktion für die Zugnummer (Zugname) finde ich essentiell.

Die Spalte(n) "Hinweis" sind etwas verwirrend und könnte mehrdeutig sein:
- Status zur Verarbeitung durch das Plugin (verarbeitet)
- Hinweistext im Fahrplan (Bsp S6 Bern – Schwarzenburg)
- Hinweistext vom Spieler (Bsp +5, Abwarten eines anderen Zuges, von PianoRailways, Bern)
- Hinweis ob "einfahrt" oder "ausfahrt"

- ggf könnte man auch hier erweitern, dass der Status des Zuges (ob bereit, am Fahren, am Bahnsteig, vor rotem Signal, im Gleisbild, noch gar nicht hier aber im Fahrplan) auch noch angezeigt wird, mit Symbol oder farblich.

Und wie arbeitet dieses Modul? Aktualisierung nach einer gewissen Zeit oder Aktualisierung bei einem Event, wie jTrainGraph z.B.

**Comment by topological-state** [comment]
das modul zeigt den fahrplan nach korrektur der einfahrten und verspätungen an, so wie er von allen modulen verwendet wird. der fahrplan wird periodisch vom simulator abgefragt und aktualisiert. ereignismeldungen beeinflussen den fahrplan nicht.

das modul dient in erster linie zum überprüfen der korrekturalgorithmen. für den spielgebrauch sehe ich momentan keinen mehrwert gegenüber den fahrplänen im simulator. allenfalls könnte es später dazu dienen, die verspätungen manuell zu korrigieren, z.b. bei überholungen oder kreuzungen.

die hinweisspalte werde ich wieder entfernen, wenn sie verwirrend ist.
