### ISSUE TITLE
Darkmode?

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#16]
Darkmode wäre nice :)

**Comment by topological-state** [comment]
gibt durch die matloblibrc datei jetzt einen darkmode. unter linux kommt der automatisch. unter windows die datei ins .matplotlib-verzeichnis kopiert werden, siehe hier: https://matplotlib.org/stable/users/faq/troubleshooting_faq.html#matplotlib-configuration-and-cache-directory-locations

sollte bei gelegenheit benutzerfreundlicher gemacht werden...

**Comment by topological-state** [comment]
ich werd's demnächst als standard implementieren...

**Comment by PianoRailways** [comment]
OMG, ich lieb's <3 danke

**Comment by topological-state** [comment]
:+1:
