### ISSUE TITLE
Fahrplanmodul: Verspätung von Folgezügen wird anschliessend nicht richtig aufgeichnet

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#17]
Sobald ein Zug ein Folgezug ist, so wird die Verspätung bei "Züge" zwar noch richtig angezeigt, im Fahrplan von Zug X wird jedoch noch die Verspätung von vorher angezeigt. Somit funktioniert auch die Prognose des Folgeszuges des Folgezuges nicht mehr sobald ein Zug ein Folgezug ist.

**Comment by topological-state** [comment]
sollte jetzt besser sein.

**Comment by PianoRailways** [comment]
Die Verspätung wird immer noch nicht aktualisiert bei Folgezügen. Im linken Tab "Züge" stimmt weiterhin alles. Im rechten Tab "Fahrplan xxxxx" steht immer noch die berechnete Verspätung und wird nicht aktualisiert.
Ein Folgezug muss nicht immer eine höhere Zugnummer oder ZID haben als ein Vorgänger, falls dies hilfreich sein könnte.

**Comment by topological-state** [comment]
in welchem stellwerk?

**Comment by topological-state** [comment]
ich habe die verspätungsberechnung komplett überarbeitet. das problem sollte gelöst sein.
