### ISSUE TITLE
gleisbelegung: make hover event instead click?

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#2]
at the "gleisbelegung" I can click a train and get further information about.
But I can't "unclick" this train so that the yellow information box disappears e.g. by clicking in a empty spot or reclicking the same train.

Maybe it would be interesting, if the information will also show up when hovering over a specific train.

**Comment by topological-state** [comment]
i'll stick to clicking rather than hovering because i want the message box to stay. but yes, there will soon be a way to make it disappear.
