### ISSUE TITLE
Vorgänger stehen länger in der Gleisbelegung als der Nachfolger

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#20]
Neuerdings stehen Züge überlagert in der Gleisbelegung. Handelt es sich um das gleiche Fahrzeug, so wird korrekterweise kein Konflikt erkannt. Allerdings scheint der Vorgänger länger dazustehen als der Nachfolger. 
![image](https://user-images.githubusercontent.com/32222604/171065817-7a144e87-90cb-4a78-9f6c-d0fda63d73c1.png)

**Comment by topological-state** [comment]
sollte in der neusten version behoben sein.
