### ISSUE TITLE
Plugin crasht, ev. etwas wegen fehlender Anlagenconfig?

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#21]
Plugin crasht. In der Log-Datei steht etwas von fehlender Anlagenkonfiguration.
```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PianoRailways\\.stskit\\126.json'
2022-05-31 00:56:33,516 (anlage) ERROR: fehler beim laden der anlagenkonfiguration
Traceback (most recent call last):
  File "E:\PianoRailways\Downloads\stskit-master\anlage.py", line 164, in update
    self.load_config(config_path)
  File "E:\PianoRailways\Downloads\stskit-master\anlage.py", line 436, in load_config
    with open(p) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PianoRailways\\.stskit\\126.json'
2022-05-31 00:57:05,234 (anlage) ERROR: fehler beim laden der anlagenkonfiguration
Traceback (most recent call last):
  File "E:\PianoRailways\Downloads\stskit-master\anlage.py", line 164, in update
    self.load_config(config_path)
  File "E:\PianoRailways\Downloads\stskit-master\anlage.py", line 436, in load_config
    with open(p) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PianoRailways\\.stskit\\126.json'
```

**Comment by topological-state** [comment]
nein, die fehlende konfiguration wird abgefangen. es muss an was anderem liegen, ich kann es aber bei mir nicht reproduzieren. in welchem stellwerk tritt das auf (bitte immer angeben)?

**Comment by PianoRailways** [comment]
In diesem Fall war es auf der Übeinstanz von rbs / Worblaufen. Passierte
nach wohl so 20 Minuten und dann später nochmals.
Aber auch schon in anderen Stellwerken sind die Fenster einfach so
abgeschmiert.

topological-state ***@***.***> schrieb am Di. 31. Mai 2022 um
19:01:

**Comment by topological-state** [comment]
crash ist behoben, die ursache - ein zug ohne nachgeführte verspätung - aber nicht. muss ich noch untersuchen.

**Comment by PianoRailways** [comment]
Was bewirkt die Anlagenkonfiguration eigentlich? Und muss man das Plugin mit Adminrechten ausführen, damit diese erstellt wird?

**Comment by topological-state** [comment]
die anlagekonfiguration fasst gleise zu bahnhöfen zusammen, gruppiert ein- und ausfahrten und definiert die strecken, die (später) im bildfahrplan dargestellt werden können. die konfiguration kann nicht einfach aus der schnittstelle ausgelesen werden und muss teilweise vom benutzer angepasst werden. in der aktuellen version ist die konfiguration aber noch kaum sichtbar.

die konfiguration wird beim schliessen des hauptprogramms im {$home}/.stskit-verzeichnis abgelegt. administratorrechte werden nicht benötigt.

**Comment by PianoRailways** [comment]
Falls definiert werden muss, welche Strecken im Bildfahrplan dargestellt
werden, kann ich auch helfen, manuell etwas zu schreiben. Dabei denke ich
v.a. an die Darstellung von z.B. Anschlüssen, nimmt man sich
Hauenstein/Sissach als Beispiel, so sollte man auch die Möglichkeit haben,
den Anschluss der S9 auf der grossen Strecke sichtbar zu haben. Wie dies
genau original gemacht wird weiss ich nicht :/ Ich persönlich überlagere im
jTrainGraph teilweise auch Strecken und markiere sie farbig, so habe ich
alles sichtbar, für aussenstehende zwar nicht sehr einfach lesbar, aber ich
hab alles drauf.

Am Sa., 4. Juni 2022 um 17:20 Uhr schrieb topological-state <
***@***.***>:

**Comment by topological-state** [comment]
mein plan ist, die strecken nebeneinander darzustellen, wenn es nicht zu kompliziert ist. andernfalls lasse ich mehrere fenster mit verschiedenen strecken zu.

ich schliesse diesen issue jetzt mal. für wünsche und ideen gibt es jetzt die "discussions" seite in der github-menüleiste.
