### ISSUE TITLE
VAb wird von Station vorher angezeigt

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#23]
Das Update mit VAn und VAb ist super!

Wenn ein Zug auf einen Gegenzug warten muss, so wird dies dort im Nachhinein ersichtlich. Allerdings wird nicht eindeutig ersichtlich, wo genau der Gegenzug abgewartet werden musste.

Mein Beispiel in rbs / Worblaufen:
![image](https://user-images.githubusercontent.com/32222604/172020491-b42bb214-8997-4293-87fc-7c4a8638a74a.png)
Der Zug musste in WBL2 auf den Gegenzug warten, nicht in BNTI. Sobald ein Zug also in WBL2 angekommen ist (Events sollte ja gesendet werden), so sollte die Ankunftsverspätung nicht mehr geändert werden, denn der Zug steht ja nun dort.

**Comment by PianoRailways** [comment]
Wenn Fahrzeitreserve eingebaut ist, ein Zug also weniger Zeit für eine Strecke braucht, der Fahrplan jedoch mehr einberechnet hat, so wird die Ankunftsverspätung bzw. die Abfahrt am vorherigen Bahnhof nicht korrekt aufgezeichnet.
Die Abfahrtsverspätung in MUEB wäre hier auch +2 gewesen, die Ankunft in ZOL jedoch +0, ebenfalls die Abfahrt. Man kann also nicht darauf schliessen, dass VAb(MUEB) = VAn(ZOL) ist. 
![image](https://user-images.githubusercontent.com/32222604/175673569-7a207e6f-ad85-4e0e-990c-38a9621e6539.png)

**Comment by topological-state** [comment]
sollte mit dem neusten update besser sein

**Comment by topological-state** [comment]
hier wurde ein zug nach ausfahrt biberist angehalten:

![Screenshot from 2022-07-16 15-29-00](https://user-images.githubusercontent.com/51272421/179360513-3c59ecbd-8aa3-4412-a267-d603dd014d6c.png)
