### ISSUE TITLE
Plugin Absturz

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#24]
Im Stellwerk Neuchâtel gab es einen Crash. Von der Spielzeit war es etwas zwischen 14:40 und 15:00. Auch andere Plugins sind abgestürzt (jTrainGraph). Ev. gibt es wieder einen Zug mit Hinweistext mit Umlauten oder so, wie auch schon im Forum diskutiert wurde.

**Comment by PianoRailways** [comment]
Die Verspätungsmeldung `Attente d'un autre train` scheint bei mir den Fehler auszulösen, auch bei anderen Plugins.

**Comment by topological-state** [comment]
die fehlermeldung lautet:

`xml.sax._exceptions.SAXParseException: <unknown>:1:0: undefined entity`

beispiel xml vom sim:

`<zugdetails usertextsender='Solothurn, bummler' zid='103415' verspaetung='0' gleis='SO1' amgleis='true' von='Langendorf' usertext='türstörung, +3&rsquo;' name='7733' nach='HRK 651' plangleis='SO1' sichtbar='true' />`

ist also ein fehler in den plugins.

**Comment by topological-state** [comment]
kleine hintergrundinfo für die nachwelt: `&rsquo;` wie vom sim gesendet, ist eigentlich nicht gültiges xml, ausser es wäre in einer DTD deklariert. alle gängigen xml-parser melden daher zu recht einen fehler. eine DTD ist in einer streaming-anwendung wie dieser aus performancegründen nicht sinnvoll. damit das parsing funktioniert, dürfen daher nur numerische (unicode) zeichenreferenzen verwendet werden. entweder diese kommen schon so vom server, oder (wie hier gemach) der client löst die referenzen vor dem parsing auf.

**Comment by PianoRailways** [comment]
Ebenfalls Doppelpunkte in der Verspätungsbeschreibung scheinen in den Plugins Fehler auszulösen
