### ISSUE TITLE
Ist-Verspätung bei Folgezügen

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#25]
Nachtrag zu Issue #17

Folgezüge werden nun besser berechnet, kann ein Folgezug jedoch anschliessend mehr Verspätung aufholen als erwartet/berechnet (auf der Strecke oder am Endbahnhof), wird die Ist-Verspätung aber auch nicht mehr richtig nachgeführt.

**Comment by topological-state** [comment]
immer noch?

**Comment by PianoRailways** [comment]
Die Ist-Verspätung wird nun viel besser nachgeführt ja.

Allerdings die Prognose nicht. Dann entstehen lustige Graphen 
![image](https://user-images.githubusercontent.com/32222604/178138757-e8cc4d85-7437-4d67-8d3d-7c1291893a0c.png)
![image](https://user-images.githubusercontent.com/32222604/178139390-6e895d04-3185-48c4-b54d-bd4b978c44d9.png)

**Comment by topological-state** [comment]
habe ich heute auch gesehen. muss ich mir anschauen.

**Comment by topological-state** [comment]
habe den fehler endlich gefunden. funktioniert jetzt hoffentlich...

**Comment by PianoRailways** [comment]
Aktuell besteht das Problem irgendwie wieder
