### ISSUE TITLE
Vorschlag: Weniger fette Balken in Gleisbelegung

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#26]
Gäbe es ev. eine Möglichkeit, die Züge in der Gleisbelegung weniger fett darzustellen sondern etwas dezenter, aber dennoch gut lesbar?
![image](https://user-images.githubusercontent.com/32222604/172046126-bd255526-b9df-48af-88c4-5893cff1c302.png)
Quelle: https://bahninfrastruktur.sbb.ch/content/dam/internet/bahninfrastruktur/de/produkte-dienstleistungen/bahninformatiksysteme/bahnbetrieb/Broschuere-RCS-DISPO.pdf.sbbdownload.pdf

**Comment by topological-state** [comment]
danke für die broschüre - habe ich noch nicht gekannt.
klar, kann man die grafik anders gestalten. aber ich habe im moment andere prioritäten.

**Comment by topological-state** [comment]
mir gefällt es, wie es ist. ich schliesse den issue.
