### ISSUE TITLE
"Hinweis" Spalte

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#29]
Wie unter #15 erwähnt, war es verwirrend, was die Spalte "Hinweis" im "tabellarischen Fahrplan" genau sollte (Hinweis ob abgearbeitet?, vor Rot? Spielermitteilung? etc...)

Es wäre ggf. hilfreich, wenn diese Spalte genutzt wird, um den aktuellen Status darzustellen (Fahrplanevent bereits abgearbeitet?), denn aktuell ist nicht ersichtlich, bei welchem Fahrplanevent ein Zug aktuell ist. Kann ruhig auch einfach ein Kästchen sein mit einem Tick drin, falls dieser Eintrag bereits abgeschlossen ist.

**Comment by topological-state** [comment]
der status wird jetzt farblich dargestellt.
