### ISSUE TITLE
Lücke in der Grafik (Huttwil 651, Lindenholz (LHO) fehlt

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#31]
Komisch, da fehlt irgendwie die Haltestelle Lindenholz 
![image](https://user-images.githubusercontent.com/32222604/175664282-b8a2e650-6082-4904-925e-13283fa43bb8.png)

**Comment by topological-state** [comment]
sollte jetzt behoben sein. noch hartnäckiger ist GT/GBA, wo ich keine möglichkeite sehe, die reihenfolge aus dem gleisplan herauszulesen. ich mache es dort (allgemein bei mehrdeutigen gleiskonfigurationen) über den zugfahrplan. dazu muss aber erst mal ein zug im fahrplan erscheinen...
