### ISSUE TITLE
Bildfahrplan: Bahnhofsbezeichnung mit Gleisnummer statt nur Abkürzung (Seeland Ost 374)

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#32]
Bei mir wird der "bildfahrplan LGUT-BI" ziemlich gut dargestellt. Der Bahnhof "Lyss" wird mit "LY1" abgekürzt. Alle anderen haben korrekt nur die Abkürzung, nur eben Lyss irgendwie nicht.

**Comment by topological-state** [comment]
das kommt vor, wenn ein bahnhof nicht-zusammenhängende gleise hat (nachbarrelation) oder wenn ein anschlussgleis auch mit LY beginnt. dann musst du den bahnhof in der konfigurationsdatei manuell zusammenfügen. siehe hier: https://github.com/topological-state/stskit/wiki/Configuration. ich sehe leider keine möglichkeit, das automatisch und konsistent zu machen. irgendwann wird's hoffentlich ein GUI für die konfiguration geben.
