### ISSUE TITLE
Einfahrten aktualisieren keine Live-Daten

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#33]
Kommt ein Züg früher als vom System (oder vom Plugin?) erwartet, so löst dies keine Verspätungkorrektur aus (weder im tabellarischen- noch im grafischen Fahrplan. Dadurch entsteht eine komische Linie in der Grafik:
![image](https://user-images.githubusercontent.com/32222604/175668134-244a2ef6-75b5-4d59-982e-d7135e322fd8.png)
![image](https://user-images.githubusercontent.com/32222604/175668153-924bad2c-4231-48eb-9a64-052c180340b3.png)

**Comment by topological-state** [comment]
die vom simulator gemeldete verspätung kann bis zum erreichen des ersten wegpunkts sehr ungenau sein. das plugin berechnet die verspätung bei einfahrt nun selber anhand der uhrzeit. noch nicht eingefahrene züge verschwinden somit nicht mehr vom bildfahrplan, und eingefahrene züge erhalten die effektive verspätung. kleine sprünge können am ersten wegpunkt immer noch auftreten (rundungstoleranz, zeitreserven im fahrplan, langsame züge, etc.)
