### ISSUE TITLE
Blick in die Vergangenheit

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#34]
Teilweise könnte es nützlich sein, wenn man etwas mehr in die Vergangenheit sieht als nur 5 Minuten. Ich denke, 10 Minuten könnte noch gut sein.
Ideal wäre natürlich, wenn man scrollen könnte, die Daten scheinen ja zwischengespeichert zu werden (tabellarischer Fahrplan), wieso also nicht auch in der Gleisbelegung und Bildfahrplan.

**Comment by topological-state** [comment]
Einstellung der Vergangenheit ist jetzt umgesetzt. Eine Scrollbar kann ich mit den mir bekannten Techniken nicht effizient umsetzen. Die Grafik ist zu langsam.

Bei dringendem Bedarf den Issue wieder öffnen, am besten mit einem praktikablen Lösungsansatz.
