### ISSUE TITLE
Gleisplan/Bildfahrplan kann nicht richtig geladen werden (Stw. Langenthal)

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#39]
Im Stellwerk Langenthal ist die Situation etwas besonders. Es sind zwei Strecken angezeigt, nämlich die Stammstrecke via Langenthal-Herzogenbuchsee sowie die Bahn-2000-Strecke mit dem Abzweig Wanzwil. Damit jedoch der Fahrplan von Zügen auch bei Umleitungen korrekt abgearbeitet werden kann und Verspätungsanzeigen im System korrekt sind, gibt es auf der Stammstrecke ebenfalls Bahnsteigelemente, sonst würde es heissen, dass der Zug noch nicht alle Fahrplanabschnitte erledigt hat, was zu Fehlern führt.

Nun kann man im Bildfahrplan zwar WY-ROG ausgewählt werden, die erkannten Bahnhöfe sind jedoch jene der NBS. RTW, HB, LTH werden also dort nicht aufgelistet. MATA-RTR funktioniert jedoch.

Da dies von Erbauerseite aus wohl nicht geändert werden kann, da eben sonst Fehler (unerledigte Fahrplanabschnitte) entstehen, müsste man ev. auch hier den Fahrplaneinträgen in den Zügen mehr Gewicht geben oder solche doppelt vorhandene Wege gekonnt ignorieren.

Der Gleisplan sieht eben wegen diesen Doppelbahnsteigen auch etwas lustig aus
![image](https://user-images.githubusercontent.com/32222604/177838529-649fdcd3-4c51-4074-a4a9-86f49b96ce28.png)

**Comment by topological-state** [comment]
das ist ja ein rechter murks. es werden gleisverbindungen angezeigt, die gar nicht existieren. kann man nicht wenigstens unterschiedliche gleisbezeichnungen vergeben (und als nachbarn deklarieren), so dass ich die strecken unterscheiden könnte? sonst muss man die strecke von hand eingeben. und die distanzen vermutlich auch noch.

**Comment by topological-state** [comment]
eine konfigurationsdatei für langenthal ist mittlerweile im lieferumfang.

![Screenshot from 2023-03-19 20-32-44](https://user-images.githubusercontent.com/51272421/226204672-85da23df-85d6-4536-9c92-5391f9cc9460.png)

![Screenshot from 2023-03-19 20-32-49](https://user-images.githubusercontent.com/51272421/226204681-8aabf5c6-f0ea-4888-bf25-0605343173a5.png)
