### ISSUE TITLE
Bildfahrplan "Anschluss X" + "Anschluss Y" als das gleiche erkannt

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#41]
Im Stellwerk Laufental werden die Ausfahrten "Anschluss SOY", "Anschluss MST", "Anschluss GREL" und "Anschluss BAER" als ein Punkt "Anschluss" erkannt. Auch das herumspielen mit "Via" bringt nicht viel. Dadurch ist es fast nicht möglich, die gesamte Strecke korrekt darzustellen. Geht das nicht irgendwie etwas intelligenter? Es wird immer "via Anschluss" angezeigt, obwohl es definitiv noch andere Wege gibt.
![image](https://user-images.githubusercontent.com/32222604/178156998-ec050722-fc97-40e8-ab3c-a6d925472f06.png)

**Comment by topological-state** [comment]
du musst die anschlüsse manuell trennen in der konfigurationsdatei. siehe https://github.com/topological-state/stskit/wiki/Configuration
anschlüsse werden nach dem ersten wort gruppiert. sonst müsste man die anschlüsse bei doppelspur manuell kombinieren. ich nehme an, dieser fall kommt öfter vor.

**Comment by topological-state** [comment]
ich schliesse jetzt anschlüsse, die schlüsselwörter wie "abstellung", "anschluss", "depot", "gruppe" o.ä. enthalten von der automatischen gruppierung aus.
