### ISSUE TITLE
Verspätungskorrektur bei mehreren Stationen

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#42]
Zsmhang mit #38 
Es ist möglich, wenn man an einem Halt eine Korrektur durchführt, und danach an einem vorherigen Halt eine grössere Verspätung einstellt, dass die als erste korrigierte Verspätung nicht nachgeführt wird und eine lustige Linie entsteht.

![image](https://user-images.githubusercontent.com/32222604/178158336-3b9135bf-dd85-458e-a5dc-b53057534295.png)

**Comment by topological-state** [comment]
beim setzen einer korrektur werden die nachfolgenden jetzt gelöscht. man kann eine korrektur auch mittels 0-(null)-taste löschen. korrekturen werden durch quadratische symbole angezeigt.

**Comment by PianoRailways** [comment]
Fehler besteht immer noch.
Schritt für Schritt:

1. Verspätung ab SF auf +10 gesetzt
2. Verspätung ab BWA auf +3 gesetzt
![image](https://user-images.githubusercontent.com/32222604/179348552-eb017cfc-e9e5-449d-934b-2bb2732bb12e.png)

Dass eine gesetzte Verspätung nie weniger als vom System gegeben (in dem Fall war es +1 prognostiziert) betragen kann funktioniert. Ob dies jedoch so soll?
