### ISSUE TITLE
Gleisbelegung, Abfahrtsverspätung

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#43]
Im Zusammenhang mit #28 fehlt in der Gleisbelegung die prognostizierte Abfahrtsverspätung. Aktuell wird nur die Ankunftsverspätung angezeigt. Die Darstellung der Abfahrt ist korrekt, jedoch fehlt eben die Zahl der Abfahrtsverspätung, wäre auch gut im Stil von (+10 | +5)

**Comment by topological-state** [comment]
verspätung wird grafisch und im detailfeld angezeigt. die grafik scheint mir viel übersichtlicher so.
