### ISSUE TITLE
Zug tauscht Lok, Prognose zu optimistisch

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#44]
Wenn im Basler RB ein Zug massiv Verspätung hat, so warte ich i.d.R. bis der Zug tatsächlich da ist, bevor ich die Ersatzlok hervorhole. Dann kann es auch sein, dass dieser verspätete Zug dann halt noch 10 Minuten auf die Lok warten muss. Die Gleisbelegung berechnet, da A Flag vorhanden meistens, dass der Zug mit viel weniger Verspätung (oder einfach pünktlich) abfahren kann. Eventuell wird ja gemeldet vom Sim, ob ein Zug ein Lokwechsel macht und wie viel Verspätung diese Lok hat.

**Comment by topological-state** [comment]
lokwechsel ist im fahrplan vermerkt. die ersatzlok und wie viel verspätung sie hat, erfahre ich aber nicht. ich setze bei lokwechsel die mindestaufenthaltsdauer pauschal auf 5 minuten.

ich habe vor, die abfahrtskorrekturen auch in der gleisbelegung einzuführen. dann könntest du die abfahrt selber anpassen. denkbar ist auch, die mindestaufenthaltsdauer pro stellwerk konfigurierbar zu machen. ich bin aber kein gui-experte. das wird dauern...
