### ISSUE TITLE
Gleisbelegung: Gleisbelegungskonflikt, obwohl es ein Nachfolger ist.

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#47]
In Chur Spielzeit ca. 09:10 Uhr.
![image](https://user-images.githubusercontent.com/32222604/180620001-193b75a8-6010-4c46-bb86-773ebdc1ab36.png)
Die Züge werden als Konflikt dargestellt, es handelt sich dabei jedoch um einen Nachfolger, was doch vom System erkennt werden sollte?
![image](https://user-images.githubusercontent.com/32222604/180620041-41a46703-7497-4cfe-8206-b7299022eda0.png)

**Comment by topological-state** [comment]
es wird im moment nur ein vorgang (ersatz/kuppeln/flügeln) erkannt. werde ich bei gelegenheit verbessern.

**Comment by topological-state** [comment]
kann ich nicht (mehr) reproduzieren. kupplung 1420/1425 wurde heute wie erwartet dargestellt.
