### ISSUE TITLE
Ein- und Ausfahrten (Grafik) bündeln

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#48]
Es wäre praktisch, wenn die grafische Anzeige der "einfahrten" und "ausfahrten" beide anzeigen würde, dies würde z.B. Basel SBB | Basel RB etwas erleichtern. Natürlich müsste da jeweils auch ersichtlich sein, ob es sich um ein Ein- oder Ausfahrt des Zuges handelt, z.B. mit einer Markierung (Pfeil?) oder so. Dies wurde es erleichtern, indem man nicht mehrere Fenster nebeneinander haben muss und vergleichen muss, wann wo jetzt etwas kommt/geht.

**Comment by topological-state** [comment]
mein plan ist, die ein- und ausfahrten (konfigurierbar) im gleisbelegungsfenster zu integrieren.

**Comment by topological-state** [comment]
ein- und ausfahrten sind jetzt im gleichen fenster zusammengelegt.
