### ISSUE TITLE
Bildfahrplan: Züge erst darstellen wenn im Stellwerk

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#49]
Es wäre ggf. hilfreich, wenn die Linienstärke im Grafischen Fahrplan unterschiedlich sein könnte, wenn ein Zug bereits im Stellwerk sichtbar ist oder eben nicht. Manchmal kommt es vor, dass das STS System etwas spinnt oder die Verspätung beim Nachbarn nicht aktualisiert wird. So könnte man auf einen Blick sehen, ob der Zug bereits fix so im eigenen Stellwerk verkehrt wie man es geplant hat, oder ob dies einfach eine Schätzung ist und der Zug noch beim Nachbarn ist.

**Comment by PianoRailways** [comment]
Oder hat sich dies ev mit #33 erledigt?

**Comment by topological-state** [comment]
die nicht eingefahrenen züge sollten jetzt nicht mehr oberhalb der aktuellen zeitlinie beginnen. von daher sollte eine unterscheidung möglich sein. ich bin eher gegen eine spezielle markierung - mehr aus ästhetischen gründen.

**Comment by PianoRailways** [comment]
die spezielle Markierung war vor allem gedacht, um Züge, die noch nicht
eingefahren sind aber dennoch mit der prognostizierten Zeit dargestellt
werden zu erkennen. Da nun jedoch die Züge frühstens bei der Jetzt-Linie
beginnen, erübrigt sich diese Markierung auch für mich, muss ich gleich mal
testen :)

Am Mi., 3. Aug. 2022 um 21:42 Uhr schrieb topological-state <
***@***.***>:
