### ISSUE TITLE
add_fahrzeit

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#5]
What does "add_fahrzeit(trainnumer, einfahrt, bahnsteig, time)" mean and what is it for?

**Comment by topological-state** [comment]
(it's a debug message.) the program collects actual run time between stations for statistics. the main purpose is to make better prediction of entry and exit times. you may see that the entry times in the einfahrten window are more accurate after a few trains have passed (noticeable if the stations is far away from the entry point). however, times are measured between tracks and not stations, and trains with rare track relations miss the correction. this is something i'm working on.
