### ISSUE TITLE
Bildfahrplan: Nicht verwendete Gleise werden nicht angezeigt

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#50]
Hat ein Gleis keinen Zug, so wird dieses in der Gleisbelegung gar nicht angezeigt, was die Suche nach einem freien Gleis erschwert.
![image](https://user-images.githubusercontent.com/32222604/182953016-9f2abfd0-b0f3-4575-afab-b4e4ee1498e0.png)

**Comment by topological-state** [comment]
ich arbeite daran, das konfigurierbar zu machen. auch im zusammenhang mit #48 . ausserdem will ich konfliktgruppen einführen, so dass konflikte auf gleisabschnitten (a/b, kurz/lang) auch angezeigt werden.

**Comment by topological-state** [comment]
die gleise können jetzt ausgewählt werden: einfach mit dem toolbutton in die einstellungen wechseln.
