### ISSUE TITLE
Folgezug wird nur 1 Minute lang angezeigt

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#51]
Wechselt ein Zug auf einen Folgezug, so wird dieser Folgezug in der Gleisbelegung nur mit einem Aufenthalt von einer Minute angezeigt. Eigentlich könnte man doch, sobald der Wechsel stattgefunden hat, bereits den neuen Zug darstellen.

**Comment by topological-state** [comment]
es steht häufig so im fahrplan. der zug wechselt die nummer zu einer bestimmten zeit und ist dann gleich abfahrbereit. ich verlängere die aufenthaltsdauer auf mindestens 1 minute, damit man die nummer sieht.

**Comment by PianoRailways** [comment]
Dann stimmen wohl die Daten der API nicht überein mit dem, was tatsächlich
verbaut ist.
Die Fahrplaneinträge werden normalerweise so gemacht, dass ein ankommender
Zug unmittelbar den E-Flag ausführt.

topological-state ***@***.***> schrieb am Sa. 6. Aug. 2022 um
16:44:

**Comment by topological-state** [comment]
im fahrplanfeld des simulators steht's auch so. z.b `15:39-` beim ersten zug und `15:45-15:45` beim folgezug. ich schliesse daher den issue.
