### ISSUE TITLE
Toolbuttons Hovertext nicht sichtbar

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#52]
Wenn ich über die Buttons in der Toolbar gehe, wird zwar ein Fensterchen angezeigt, allerdings erscheint kein Text darin. 
![image](https://user-images.githubusercontent.com/32222604/185713191-cf8a6d27-89ea-4f73-a48b-5a6efbf7a68d.png)

**Comment by topological-state** [comment]
weiss auf weiss kann man schwer lesen...

**Comment by topological-state** [comment]
problem gelöst?

**Comment by PianoRailways** [comment]
Problem behoben
