### ISSUE TITLE
Wann wird die Anlagenconfig aktualisiert?

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#53]
Mir ist aufgefallen, dass der Bildfahrplan scheinbar noch immer alte Bahnsteige/Haltepunkte beinhaltet, die während dem Umbau des Stellwerks Bülach in Gebrauch waren bzw. mit Tippfehlern versehen waren. Diese sind jedoch nun im Stellwerk entfernt. Nach einem Reload des Plugins taucht nun dieser zwar nicht mehr auf, jedoch fehlen einige Haltepunkte.
KAAG ist im Bildfahrplan sichtbar, RUEN und MELN jedoch nicht, diese liegen alle in einem Block. Siehe Vorschaubild: https://www.stellwerksim.de/shot/see_449.jpeg

Ebenfalls gibt es Güterzüge mit einem eingetragenen Halt (mit A-Flag) in Weiach-Kaiserstuhl. WK wird jedoch als zwei separate Bahnhöfe im Bildfahrplan dargestellt und kein Zug scheint einen Halt eingetragen zu haben.

Da das Stellwerk aktuell leider noch nicht sichtbar ist wird eine Fehlerreproduktion wohl schwieriger :/

**Comment by topological-state** [comment]
in diesem fall löschst du am besten die anlagenkonfiguration ${HOME}/.stskit/449.json manuell. sie wird beim neustart neu erstellt.

in der aktuellen programmversion führt eine änderung der build-nummer zu einer warnung im logfile. die konfiguration wird aber trotzdem geladen und kann zu fehlenden gleisen führen. ich sollte die warnung wohl etwas sichtbarer machen.

die zwei gleise von WK kannst in der konfigurationsdatei deklarieren, wenn das beim neustart nicht automatisch passiert.

bezüglich bildfahrplan kann ich noch nicht viel sagen. mehrere haltepunkte in einem blockabschnitt sind problematisch, da ich mich v.a. auf den fahrstrassengraphen abstütze. dort wird es so aussehen, dass RUEN und MELN an zwei verschiedenen fahrstrassen liegen, RUEN vor signal 200 und MELN vor signal 232. das ist die gleiche darstellung, wie wenn die strecke zwei richtungsgleise hätte. ohne da noch viel KI aufzuwenden, wird die lösung wohl auch auf eine manuelle konfiguration hinauslaufen (die noch nicht vollständig unterstützt wird).
