### ISSUE TITLE
Verspätungsdarstellung in der Gleisbelegung

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#54]
Die Idee mit dem grafischen Darstellen der Verspätung eines Zuges in der Gleisbelegung ist eine gute. Allerdings ergeben sich bei massiven Verspätungen (kaputte Instanz mit bis +140) Darstellungen, die mehr einem defekten Display gleichen 
![image](https://user-images.githubusercontent.com/32222604/186447062-07330e34-db22-400a-a19c-c4da29f9b2a5.png)
Einen besseren Vorschlag habe ich aktuell aber leider auch grad nicht wirklich.

**Comment by topological-state** [comment]
vielleicht sollte man die länge der linie begrenzen (und dann anders markieren). die frage ist, was für ein information will herauslesen. sicher, ob ein zug verspätet ist oder nicht, und ob die verspätung kurz oder lang ist. ob ein zug 20 oder 120 minuten verspätung hat, interessiert mich hier weniger.

ich werde ein paar varianten ausprobieren.
