### ISSUE TITLE
Gleisbelegung: Gruppierung von Sektorengleisen.

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#55]
Seit a6f433a41cdc7b38c612a32007a1b1e43f396c17 werden Sektorgleise gruppiert. Die Gleise werden trotzdem separat geführt, verhalten sich bei Konflikten aber korrekterweise, als wäre es ein Gleis (bspw. BN 10 + BN 10 kurz).

Gleise 12 + 32 werden jedoch nicht als gleiche erkennt. Die sind zwar auch einfach kürzer und geteilt (quasi Sektor A und B (oder so)), ein langer Zug beansprucht jedoch beide (IR16 immer zur halben Stunde in Bern).

Ob dies überhaupt automatisch erkennt werden kann?

**Comment by topological-state** [comment]
die erkennung geschieht anhand des gleisnamens: wenn die namen zweier gleise bis zur gleisnummer identisch sind, werden sie als zusammengehörige sektoren markiert. bei BN 12/32 oder auch 2/22 geht das nicht.

die automatische gruppierung wird nur durchgeführt, wenn sie in der konfigurationsdatei fehlt. man kann sie dort also auch von hand abändern. am besten mal stskit in einem stellwerk starten und beenden, dann die konfigurationsdatei suchen (.stskit folder), die struktur studieren und abändern. falls was schief geht, datei löschen - sie wird dann neu erstellt.
