### ISSUE TITLE
Vordefinierte Strecken sind umgekehrt

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#58]
Im Bildfahrplan gibt es nun ja vordefinierte Strecken. Sind diese automatisch oder kann man sich da auch selber welche machen?
Und mir ist aufgefallen, dass diese meistens gerade falsch herum sind als es vom Gleisbild her ist. Bspw. Luzern-Zäziwil statt Zäziwil-Luzern.

**Comment by topological-state** [comment]
die vordefinierten strecken stehen in der konfigurationsdatei. sie werden automatisch erstellt, wenn der betreffende abschnitt in der konfigurationsdatei fehlt oder leer ist. man kann sie aber auch manuell erstellen oder abändern.

regeln:
- die bahnhofnamen müssen so geschrieben werden, wie sie unter `bahnsteiggruppen` deklariert sind.
- benachbarte bahnhöfe sollten im gleisplan mit einer verbindungslinie mit fahrzeitangabe versehen sein, sonst stimmt die distanz nicht.
- ein bahnhof kann auf einer strecke max. zwei mal vorkommen (z.b. NPAR in LTHA - OEEN - SOAS).

start und ziel der automatischen strecken sind alphabetisch geordnet. die pluginschnittstelle sagt nichts bezüglich orientierung der gleisanlage. allenfalls könnte ich beide orientierungen erstellen lassen.

irgendwann wird es ein drag-n-drop interface für die streckendefinition geben.
