### ISSUE TITLE
Tabellenfahrplan: Titelzeilen noch falsche Farbe

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#59]
Im Zusammenhang mit ec630f19899fd8a3efa112db7c7c42f783c97725 haben nun die Titelzeilen immer noch die weisse Farbe.
![image](https://user-images.githubusercontent.com/32222604/187068477-2ecdda11-6cfb-4c37-b1bb-1c45c413364a.png)

**Comment by topological-state** [comment]
die einstellungen sind relativ mühsam, vor allem, weil bei mir der untergrund automatisch auf alle elemente angewendet und angepasst wird. ich habe z.b. auch keine weissen check-boxes, und ich weiss nicht, wie man die dunkel machen müsste.

schreib einfach, wenn noch etwas schräg aussieht.
