### ISSUE TITLE
Gleisbelegung: Folgezüge trotz Aufenthalt verspätet

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#6]
In der Gleisbelegung werden die Folgezüge richtig erkannt. Dabei werden sie jedoch ebenfalls als verspätet angezeigt, wenn sie einen langen Aufenthalt haben. Ggf. könnte man abwägen, wie viel Verspätung ein Zug bei wie viel Aufenthalt aufholen kann.
![image](https://user-images.githubusercontent.com/32222604/163537412-913ee080-9411-4e39-a3c6-781b5e7539a7.png)

**Comment by topological-state** [comment]
gute idee. bei verspätungen über 5 minuten wird das schon gemacht (aufenthalt auf 5 minuten reduziert). ich kann das noch etwas verallgemeinern.

**Comment by topological-state** [comment]
resolved in a32ba9a
