### ISSUE TITLE
Programm langsam

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#60]
Nach einigen Stunden Spielzeit wird das Programm sehr langsam und zieht laut Taskmanager viel "Stromverbrauch". Während dem Schreiben dieses Issues ist es nun sogar gecrasht.

**Comment by topological-state** [comment]
braucht weitere tests. bei mir (ubuntu linux 20.04, python 3.10) sehe ich keine performance-verschlechterung. kommt es nur im online-modus vor?
