### ISSUE TITLE
Bildfahrplan: Nyon

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#67]
Ich bringe im Stellwerk Nyon egal mit welchen Einstellungen keine durchgehende Grafik hin irgendwie. Entweder nur der Lémanexpress GE-COP oder ab NY bis MOR.

**Comment by topological-state** [comment]
sieht aktuell so aus bei angabe der endpunkte.

![Screenshot from 2023-01-08 18-42-44](https://user-images.githubusercontent.com/51272421/211213385-6a760e00-87bc-4669-9b27-8665cbe4d96e.png)

ein paar halte des lémanexpress fehlen. diese müssen manuell definiert werden:

![Screenshot from 2023-01-08 19-27-30](https://user-images.githubusercontent.com/51272421/211213408-46ad2654-2eae-42fd-99bd-a10bbc92b036.png)

ich schliesse den issue, weil ich gerade keinen besseren lösungsansatz habe.
