### ISSUE TITLE
Einfaches executable zum downloaden erstellen

### ISSUE THREAD

**Issue by kmodexc** [topological-state/stskit#68]
Währe super, wenn es ein einfaches "all-in-one" executable gäbe. [pyinstaller](https://pyinstaller.org/en/stable/) kann sowas machen. Ich kann mich auch darum kümmern wenn es erwünscht ist.

**Comment by topological-state** [comment]
kannst gerne ein pyinstaller-skript schreiben.

ich wollte damit noch warten, weil die konfiguration des programms im moment noch nicht ganz einfach ist und gewisse computerkenntnisse erfordert.

**Comment by PianoRailways** [comment]
fänd ich auch super, da ich nicht mehr weiss, was ich schon installiert hatte und was ich wie zusätzlich installiert hab. hätte lust, das plugin auch auf dem laptop zu haben und nicht nur auf dem pc.

**Comment by topological-state** [comment]
pyinstaller-skript ist ab 01aadf8c vorhanden

**Comment by topological-state** [comment]
siehe [Wiki/Installation](wiki/Installation#ausf%C3%BChrbare-programmdatei)
