### ISSUE TITLE
Mehrfache Abhängigkeiten

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#69]
Aktuell kann leider nur eine Abhängigkeit zugewiesen werden. Manchmal könnte es praktisch sein, mehrere zuzuweisen. Bspw. einen Gegenzug abwarten und das Abwarten von Anschlussreisenden eines anderen Zuges.

**Comment by topological-state** [comment]
implementierung in 04453b5b bis 23aa76cf
