### ISSUE TITLE
Ticker: Folgezüge haben keine Events mehr

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#7]
Im Ticker gibt es keine Events mehr, sobald ein Zug gewendet (E-Flag) hat. Wie es bei F- und K-Flags ist, wurde noch nicht geprüft, vermute aber, es wird ähnlich sein.
Ev. ein Fehler der STS-Pluginschnittstelle?

**Comment by topological-state** [comment]
folgezüge werden eigentlich automatisch für ereignismeldungen registriert. in welchem stellwerk kommt das vor?

**Comment by PianoRailways** [comment]
In diesem Fall war es [asm / Niederbipp](https://www.stellwerksim.de/fahre-anlage.php?aid=554), ist aber glaub auch bei anderen der Fall.

**Comment by topological-state** [comment]
man darf die ereignisse offenbar erst nach dem namenswechsel registrieren, selbst wenn der zug schon vorher in der zugliste steht.

gelöst in 99416f23.

**Comment by PianoRailways** [comment]
Gleiches gilt anscheinend für die Gleisbelegung. Sobald ein Zug gewechselt hat, verschwindet er komplett aus der Gleisbelegung.

**Comment by topological-state** [comment]
ist das ein problem?
die gleisbelegung wird periodisch anhand einer zugliste vom simulator aufgebaut. wenn der simulator den zug nicht mehr in dieser liste führt, wird er nicht mehr angezeigt. das wird aber wohl nur den zeitraum der vergangenheit betreffen.

die zugliste beinhaltet übrigens manchmal unvollständige angaben. oft haben folgezüge eine id-nummer 0, anhand der man keine details anfragen kann. ich lese die id der folgezüge deshalb aus den flags. möglich, dass es deshalb in gewissen situationen (stellwerkabhängig?) zu problemen kommt, wenn kurzzeitig weder der ursprungs- noch der folgezug in der liste stehen.
