### ISSUE TITLE
Verspätung wird nicht nachgeführt

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#72]
![image](https://user-images.githubusercontent.com/32222604/194751445-5ac87011-add2-4cd1-9a79-7304eea99320.png)

Der Zug steht wegen einer Störung am Zug (orange im Fahrplan) seit einigen Minuten in PAPI. Der Sim zeigt mir die jetzige Verspätung an, das Plugin ebenfalls unter "Züge" im Tabellenfahrplan.
Im Zugfahrplan im Tabellenfahrplan und auch im Bildfahrplan wird diese Verspätung nicht nachgeführt. Sobald der Zug jedoch jetzt abgefahren ist, wird es übertragen und funktioniert wieder.
Weiss also nicht, ob dies extra ist, oder doch ein Fehler.

**Comment by topological-state** [comment]
das plugin erhält vom sim keine meldung über solche störungen. erst die abfahrt oder die abfahrbereitschaft wird gemeldet.
