### ISSUE TITLE
Random mit massiver Verspätung angekündigt

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#73]
Ein Zug wurde mir irgendwie aus unerklärlichen Gründen massiv verspätet angekündigt... 
![image](https://user-images.githubusercontent.com/32222604/194755502-57253746-3c5d-4588-9ff7-293aae23d262.png)
Ich glaube irgendwie ist die geschätzte Einfahrtszeit falsch berechnet.

**Comment by topological-state** [comment]
wenn ein zug auf dem weg zum ersten ziel an einem signal halten muss, verfälscht es die schätzung der einfahrtszeiten aller züge (aus dem mittelwert aller gemessenen fahrzeiten). könnte das der grund gewesen sein?

früher hatte ich jeweils die schnellste zeit genommen. die war auch nicht immer passend. ich muss mir da nochmal was überlegen.
