### ISSUE TITLE
angeblicher Gleisbelegungskonflikt (ev. mit nur Problem von Nach-Nachfolgezügen?)

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#74]
Ich habe die Vermutung, dass wenn Züge mehrfach einen E(/F/K?) Flag ausgeführt haben, in der Gleisbelegung nicht mehr als direkter Nachfolger erkannt werden und somit als Konflikt dargestellt werden. 
![image](https://user-images.githubusercontent.com/32222604/195984146-f0d0a1b2-f26c-4bcc-b2d9-2cbfcb22f836.png)

**Comment by topological-state** [comment]
richtig vermutet. problem sieht man auch, wenn rangierfahrten als züge dargestellt werden (z.b. bellinzona, merxferri-rhode).
sollte jetzt behoben sein.
