### ISSUE TITLE
Anschlussmatrix: wendende Züge sind doppelt aufgeführt

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#76]
![image](https://user-images.githubusercontent.com/32222604/201514723-3292b782-de34-41f3-99a9-454d6b875729.png)
2156 + 2161 ist eigentlich der gleiche Zug, 2156 endet aber hier in Bern.

**Comment by topological-state** [comment]
sollte jetzt behoben sein:
- nummernwechsel: 1 ankunft, 1 abfahrt
- kupplung: 2 ankünfte, 1 abfahrt
- flügelung: 1 ankunft, 2 abfahrten

**Comment by PianoRailways** [comment]
Es ist noch nicht ganz perfekt, es könnte aber auch an den Fahrplaneinträgen liegen, da die Züge oftmals umsetzen um den Nummerwechsel und Flügel durchzuführen. Hier ein Beispiel aus Burgdorf: 
![image](https://user-images.githubusercontent.com/32222604/202749330-2226cea0-76bf-4618-8520-3007b20ea63a.png)

**Comment by topological-state** [comment]
wird noch gefixt
