### ISSUE TITLE
Abfahrtserlaubnis

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#77]
Es könnte hilfreich sein, wenn z.B. der Zugname in der Anschlussmatrix grün wird, sobald die Abfahrterlaubnis erreicht ist. Also wenn keine Abhängigkeiten vorhanden sind einfach bei Bereitschaft. Wenn es gesetzte Abhängigkeiten gibt bzw. fix geänderte Verspätungen dann sobald dies erreich ist.

**Comment by topological-state** [comment]
so was schwebt mir auch vor.

**Comment by topological-state** [comment]
im neusten update f82aa23 werden die felder grün, wenn der anschluss erfüllt wurde.
