### ISSUE TITLE
Anschlussmatrix Gleisanzeige

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#78]
Weiss nicht, wie viel das bringt oder es überhaupt das Ziel ist, aber anzeigen, auf welchem Gleis ein Zug ist bzw wo er dann abfährt.

**Comment by topological-state** [comment]
ich sehe keinen bedarf. bei zu viel text wird's unübersichtlich.
ich will aber die felder anklickbar machen und dann zuginformationen wie laufweg und hinweistext unten einblenden.

**Comment by topological-state** [comment]
gleis kann jetzt in achsenbeschriftung eingeblendet werden, c88b7ff
