### ISSUE TITLE
Gleisbelegung crasht

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#8]
Die Gleisbelegung ist bei mir gecrasht. Es war im Züriberg, mitten im Spiel (mehr als 1h) Wann und warum genau kann nicht nachvollzogen werden. Ev. wäre es hilfreich, Logs zu implementieren, um genau solche Dinge nachvollziehen zu können.

**Comment by topological-state** [comment]
kann ich leider nicht reproduzieren. es kann aber gut sein, dass irgendwo eine wichtige fehlerbehandlung fehlt. bei einem crash gibt's im terminal meist eine stacktrace. logs helfen eher weniger, weil oft die relevante information fehlt.

trotzdem gibt's in der neusten version ein logging, das mit kommandozeilenoptionen aktiviert werden kann:
--log-level DEBUG --log-comm
zeichnet z.b. die gesamte kommunikation auf.
