### ISSUE TITLE
Anschlussstatus

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#80]
Ich nehme an, es sind noch weitere Dinge für die Anschlussmatrix in Planung. Etwas könnte der Anschlussstatus sein:
- Anschluss wird erreicht (weil alles pünktlich und so), grün
- Anschluss wartet, manuell vom Fdl so bestimmt, grün
- Anschluss wird definitiv nicht mehr erreicht, rot (und ggf. Zahl im Klammern, wie lange man warten müsste)
- Anschluss wird nicht mehr erreicht, weil Abbringer schon abgefahren ist
- Anschluss noch unsicher (z.B. Wartefrist von 5' Minuten definieren)
- kein Anschluss, grau oder schwarz, weil selber Zug oder so

**Comment by PianoRailways** [comment]
Ergänzung zu den Farben: Anschluss unsicher -> blau

**Comment by topological-state** [comment]
aktuelle version:

![Screenshot from 2022-11-18 21-52-08](https://user-images.githubusercontent.com/51272421/202817976-8d9b1b22-b1cb-4b9e-814d-35a663d49e30.png)
