### ISSUE TITLE
Güterzüge werden als Anschluss definiert

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#81]
Ich weiss nicht, inwiefern es sinnvoll ist, gewisse Zugnummern rauszufiltern, bezüglich einfache Bedienung und dass es überall funktioniert. Aber derzeit werden halt auch Güterzüge angezeigt xD Das System kann das natürlich nicht unterscheiden. Also falls nicht geplant oder irrelevant, Issue auch gerne wieder schliessen.

**Comment by topological-state** [comment]
das stört mich auch. ein anderes beispiel sind s-bahnen. vielleicht werde ich es an die zuggattungen anknüpfen, die schon im farbschema zur anwendung kommen. ich lasse den issue mal offen.
