### ISSUE TITLE
Fixverspätung durch Flags

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#84]
Ich verstehe nicht ganz, welche Flags welche Fixverspätung verursachen.
![image](https://user-images.githubusercontent.com/32222604/205433517-b037ad26-ad57-4d34-9acb-f5733af0b553.png)
In diesem Beispiel gibt es wohl irgendeine Verkettung von Flags, die eine Verspätung berechnen lassen. Ich glaube es ist kein Fehler, mehr eine Frage, welche Flags was verursachen.

**Comment by topological-state** [comment]
der richtungswechsel hat 2 minuten mindestaufenthalt und der ersatzzug 1 minute. die verspätung vom richtungswechsel wird daher beim ersatz nicht abgebaut.
es kann auch sein, dass der kuppelnde zug verspätung hat. das sehe ich hier nicht. beide situationen führen zu der gezeigten verspätung.

**Comment by PianoRailways** [comment]
Es war alles pünktlich und wurde jede Stunde genau so angezeigt.
Aber immerhin ist nun klar, wie das ganze entsteht. Wegen Reserven und so wird das eh schon vorher wieder kompensiert. Somit funktioniert alles genau wie es sollte :)
