### ISSUE TITLE
Maximale Anschlussfrist

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#86]
Ich habe gerade einen ICE, der mit +60 gemeldet ist. Natürlich macht es jetzt keinen Sinn, dass Züge diesen Anschluss für 50 Minuten oder so abwarten. Auch die maximale Anschlussfrist wäre gut einzustellen, z.B. 30 Minuten.

**Comment by topological-state** [comment]
du kannst den zug ausblenden: auf zugnamen klicken und dann H drücken oder icon "zug verbergen"
