### ISSUE TITLE
Kreuzungen im Bildfahrplan nicht mehr

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#89]
Seit dem neusten Update werden manchmal die Kreuzungszüge nicht mehr richtig dargestellt im Bildfahrplan. Manchmal gehts irgendwie, manchmal nicht. Es kann sein, dass ich mit der Anschlussmatrix an einem vorherigen Bahnhof rumgespielt habe.

![image](https://user-images.githubusercontent.com/32222604/209476942-f48a2b7f-1570-4307-a223-d57106aba79b.png)
in CF3 soll 3977 warten (Abhängigkeit in der Grafik gesetzt). Dadurch habe ich in GEC dem 3224 ebenfalls in der Grafik eine Abhängigkeit gegeben, was aber irgendwie nicht richtig angezeigt wird (auch nach mehreren Durchgängen des Systemrechners). Restart hilft auch nicht.

**Comment by topological-state** [comment]
jetzt besser?

achtung: der name des startskripts hat sich geändert: main.py -> stscharts.py

**Comment by topological-state** [comment]
nicht mehr reproduzierbar
