### ISSUE TITLE
Unterschied "halt" und "durchfahrt"

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#9]
Laut Code soll etwas italic werden wenn ein Zug durchfährt. Da kann ich aber nichts feststellen, dass irgendwie italic wäre (HALN 1)
![image](https://user-images.githubusercontent.com/32222604/164261394-22ba482b-3080-4984-816d-ad0343df9880.png)

**Comment by topological-state** [comment]
der zugname im balken wird italic und die umrandung zeigt eine unterbrochene linie.

ich weiss im moment nicht, wie in der details-box einzelne wörter anders dargestellt werden können. ich lasse den issue mal offen - vielleicht fällt jemandem eine lösung ein.

**Comment by topological-state** [comment]
ich habe die durchfahrtsgleise jetzt mal entfernt, um den text kürzer zu machen. ist aber auch nicht das wahre. suche noch nach einer besseren lösung, z.b. nur die weiter entfernten gleise weglassen.

**Comment by PianoRailways** [comment]
Das Problem ist eher, dass der Balken nicht verschwindet oder sich
ausblenden lässt. Wie gross das Popup ist ist mir egal

topological-state ***@***.***> schrieb am Mo. 16. Mai 2022 um
23:05:

**Comment by topological-state** [comment]
durchfahrtsgleise werden jetzt mit klammern markiert. lange routen werden abgekürzt.
