### ISSUE TITLE
Verspätung wird nicht nachgeführt

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#90]
Seit neustem wird die Verspätung irgendwie wieder nicht mehr korrekt nachgeführt was unschön wird. Also die Unterwegshalte werden scheinbar nachgeführt, die Ausfahrt jedoch dann nicht mehr 
![image](https://user-images.githubusercontent.com/32222604/209666199-02ef3656-4346-46c9-adae-3794be97e522.png)

**Comment by topological-state** [comment]
in welchem stellwerk?

**Comment by PianoRailways** [comment]
Es war in Chiasso

**Comment by PianoRailways** [comment]
Dies war in Chiasso. Manchmal gings irgendwie, meistens aber nicht

Am Di., 27. Dez. 2022 um 19:08 Uhr schrieb topological-state <
***@***.***>:
