### ISSUE TITLE
Verspätung wird nicht ganz korrekt nachgeführt

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#93]
Der Zug ist pünktlich unterwegs, wird auch in der Zugliste so mit 0 angezeigt. Im Fahrplan aber sei er mit +3 unterwegs. 
![image](https://user-images.githubusercontent.com/32222604/210156479-79012cd7-6c93-4edf-8050-ffaa42299817.png)
Es gab unterwegs eine Abhängigkeit, die ggf. eine Berechnung verfälschen könnte.

**Comment by topological-state** [comment]
verspaetungen koennen jetzt aufgeholt werden:

![Screenshot from 2023-01-11 22-46-43](https://user-images.githubusercontent.com/51272421/211924983-15b1f549-ea5f-4b2b-b669-e0341ee05030.png)
