### ISSUE TITLE
Einstellung wie lange die Grafik in die Zukunft gehen soll

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#95]
Bei der Anschlussmatrix ist so ein Feld "Umsteigezeit" und "Anschlusszeit" in Minuten bereits umgesetzt. Ich fände es sehr hilfreich, wenn man dies grundsätzlich bei allen Grafiken machen könnte. Also wie viel man in die Vergangenheit sehen will und wie viel in die Zukunft. Wäre viel einfacher, als die Config manuell bearbeiten.

**Comment by topological-state** [comment]
implementiert
