### ISSUE TITLE
aufgeholte Verspätung wird nicht durchgereicht bei Halt

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#98]
Stellwerk Biel: 
![image](https://user-images.githubusercontent.com/32222604/214114628-d15f54c0-7a74-4e1c-96c7-466ae0c24d0a.png)

Die Abhängigkeit zu 50032 wurde gelöscht, aber erst nachdem 7436 schon losgefahren ist. Diese Löschung scheint nicht bei der Berechnung angekommen zu sein. Auch eine neue Abhängigkeit zu 66071 ändert nichts.

**Comment by topological-state** [comment]
mögl. duplikat von #97
schau mal, ob das problem in a04535f gelöst ist. hat dafür vielleicht wieder neue probleme...

**Comment by topological-state** [comment]
funktioniert jetzt bei mir
