### ISSUE TITLE
Trasse abwarten (F) Zeit

### ISSUE THREAD

**Issue by PianoRailways** [topological-state/stskit#99]
Seit der Korrektur, dass (K) nicht mehr +1 verursacht, verursacht (F) +2 statt +1. Ausser dies ist so gewollt, eigentlich ist aber überall möglich innerhalb einer Minute abzufahren wenn der nächste Block schon wieder frei ist, ausser Einspurabschnitte oder so natürlich.

**Comment by topological-state** [comment]
ja, ist neu +2. geh mal nach deutschland, dann reicht selbst das nicht. ;-)
soll später einmal konfigurierbar werden.
